[package]
name = "juniper_hyper"
version = "0.1.0"
authors = ["Damir Vandic <info@dvic.io>"]
description = "Juniper GraphQL integration with Hyper"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_hyper"
repository = "https://github.com/graphql-rust/juniper"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7"
juniper = { version = "0.9" , default-features = false, path = "../juniper"}

futures = "0.1"
futures-cpupool = "0.1"
hyper = "0.12"

[dev-dependencies]
pretty_env_logger = "0.2"
tokio = "0.1.7"

[dev-dependencies.juniper]
version = "0.9"
features = ["expose-test-schema", "serde_json"]
path = "../juniper"
